elastic/go-ucfg

- CHANGELOG.md
- error.go
- error_test.go
- reify.go
- testdata/error/message/invalid_regexp_w_meta.golden
- testdata/error/message/invalid_regexp_wo_meta.golden
Improve regexp error messages by including the reason compilation failed
> Improve error messages for regular expressions

- CHANGELOG.md
- error.go
- reify.go
- validator.go
- validator_test.go
Check slices, strings and regular expression being empty.
updates `required` to check:
- string being not ""   intending: require requires string to be present and not empty
- pointers being set intending: pointers to struct must be set
- length of slice > 0 intending: array must be present at least one entry is required.
update nonzero to check:
- string being not "" intending: if present it must not be empty
- length of slice > 0: if array/slice present it must not be empty.
Closes #20
> Improve/fix required/nonzero validators

- error.go
- error_test.go
- getset.go
- merge.go
- merge_test.go
- opts.go
- reify.go
- testdata/error/message/parse_splice_w_meta.golden
- types.go
- variables.go
When merging configurations, content can be referenced by absolute path.
When building references there is a difference between plain references and
splices.
A splice is one or multiple references combined with plain strings
lazily composed into a string when reading the configuration its value. Spliced
values can be parsed into primitive types (bool, int, float, string) only.
References, do reference (late binding) configuration values by absolute path
including nested configurations.
If only one expansion is given for a configuration value, a reference will be
established.
> Initial support for variable expansion

- variables.go
- variables_test.go
simplify variable expansion evaluation by introducing expansionDefault/Alt/Err separating evaluation of different variable expansion operators.
> Separate op-based expansion evaluators

- CHANGELOG.md
- reify.go
- reify_test.go
Fix unpacking into top-level slice/array or unpacking into slice if
`inline`-tag is used.
> Fix unpacking configs into slices

- CHANGELOG.md
- getset.go
- getset_test.go
- merge.go
- path.go
- reify.go
- types.go
- ucfg.go
Closes #44 
- requires #43 to adapt unit test
> Add IsArray and IsPureArray checking config is an array

- CHANGELOG.md
- variables.go
- variables_test.go
- do not block if parser errors, but lexer still active
- fix parsing ':' in expansion default value
- turn '$' into universal escape character, so '}' in default
values can be escaped with '$'
- add some more unit tests
> VarExp parser fixes

- README.md
- variables_test.go
After upgrading to the latest version of libbeat, I discovered an infinite loop when loading my custom beat which has the following cfg file:
server:
url: ${SERVER_URL:http://127.0.0.1:12345}
Further investigations reveal that the application is waiting forever on this instruction:
go-ucfg/variables.go:351      lex <- sepDefToken
> FAILED test case to expand an env variable with default value that contains 2 colons

- CHANGELOG.md
- flag/util.go
Changes FlagValue.String() to handle the zero value case.
The zero value is converted to an empty string to distinguish it from the empty JSON object.
This is a go 1.7 compatibility fix to address the changes in https://github.com/golang/go/commit/3659645cb1f32d7b1eeefdb65f1339fe54f0f6eb
A related issue is: https://github.com/golang/go/issues/16694
> Print zero FlagValue as empty string

- doc.go
- error.go
- getset.go
- merge.go
- opts.go
- reify.go
- ucfg.go
- validator.go
- validator_test.go
- variables.go
Add doc comments to all public symbols exported by go-ucfg core. 
For review run `godoc -http=:6060` and point browser to `http://localhost:6060/pkg/github.com/elastic/go-ucfg/`
> Add godoc comments to ucfg core

- CHANGELOG.md
- flag/parse.go
- flag/parse_test.go
- flag/value.go
Enhance flag value parser to accept a superset of JSON, so arrays and objects
can be configured from commandline
The parser implements a superset of JSON, but only a subset of YAML by
allowing for arrays and objects having a trailing comma. In addition 3
strings types are supported:
1. single quoted string (no unescaping of any characters)
2. double quoted strings (characters are escaped)
3. strings without quotes. String parsing stops in
special characters like '[]{},:'
> Enhance flag value parsing

- CHANGELOG.md
- reify.go
- reify_test.go
- ucfg.go
- unpack.go
- unpack_test.go
- util.go
- Add Unpacker interface specializations for primitive types.
Types can implement `Unpack(bool)`, `Unpack(string)`, ... directly,
with casting and type checks being done ucfg. See unpack_test.go for some samples.
- Fix Unpacker interface not applied if some 'old' value is already present on
target and is struct implementing Unpack.
e.g.
```
type config struct {
V *myCustomConfig
}
func (m *myCustomConfig) Unpack(v interface{}) error { ... }
```
if V in this struct is pre-initialized by non-nil value, the Unpack method
was not called. Instead Unpack might actually fail, if myCustomConfig
requires an primitive value like int or string.
This has been fixed by moving the Unpacker interface test before reflection
based unpacking.
> Unpacker interface fixes and enhancements

- CHANGELOG.md
- error.go
- error_test.go
- flag/util.go
- json/json.go
- json/json_test.go
- merge.go
- reify.go
- testdata/error/message/invalid_type_top_level.golden
- testdata/error/message/invalid_type_top_level_w_meta.golden
- testdata/error/message/invalid_type_top_level_wo_meta.golden
- yaml/yaml.go
- yaml/yaml_test.go
This change adds support for config file which do not start with a map[string]interface{}. Example:
```
- module: system
metricsets: ["cpu"]
- module: system
metricsets: ["processes"]
```
The above does not have a `metricbeat.modules:` as a top entry.
Further changes:
* Prevent panic on empty config files
* Run `go fmt`
> Add support for pure array config files

- CHANGELOG.md
- merge.go
- merge_test.go
reassign key of merged sub-configs to ensure config objects generated
dynamically will be correctly merged.
=> merging sub-configs enforces strict variable expansion of settings
being affected
> Fix merging dynamically generated sub-configs

- CHANGELOG.md
- merge.go
- merge_test.go
- reify.go
- structs_test.go
- util.go
- Fix: ignore non-exported fields when merging a struct into a config
- Introduce `,ignore` struct tag option to optionally ignore exported fields
> Add support to ignore struct fields

- CHANGELOG.md
- ucfg.go
- unpack.go
- unpack_test.go
go-ucfg allows for custom typed unpackers via interfaces `BoolUnpacker`,
`IntUnpacker`, ..., `ConfigUnpacker`.
In case of the `ucfg.Config` object being rebranded, the `ConfigUnpacker`
interfaces is not usable. This change uses reflection to support some rebranded
unpacker by checking `*Config` being convertible to the first method parameter.
The interface expected must still be compatible to `ConfigUnpacker`.
With this change, this sample code can be used to unpack using a customized
config type:
```
type MyConfig *ucfg.Config
type ConcreteConfig struct {
...
}
func (c *ConcreteConfig) Unpack(in *MyConfig) error {
...
}
```
> Add support for reflection based Unpacker

- CHANGELOG.md
- error.go
- error_test.go
- errpred.go
- errpred_test.go
- fieldset.go
- fieldset_test.go
- opts.go
- reify.go
- testdata/error/message/cyclic_reference.golden
- types.go
- ucfg_test.go
- variables.go
- variables_test.go
*Cyclic reference*
This commits changes the behavior of the ucfg library when we detect
cyclic reference, before when a cyclic was defined in a configuration
the library would go into an infinite loop and panic because of the
stack.
The new behavior is the following, when a cyclic reference is detected
when resolving the reference it will try to resolve it with the other
configured resolvers (the environment and the keystore for beats). If the key
is not found in theses resolvers the error will be send back to the
users with the problematic key.
If the values is found in the other resolver it will return that value
and it wont be a cyclic reference.
The detection is using a `VisitedFieldsRecorder` that will keep track of
the paths that was required to generate the concrete value, if the …
> Better handling of cyclic reference and top level reference

- CHANGELOG.md
- reify.go
- ucfg_test.go
Fix was to make sure when we call `doReifyPrimitives` we need to clear
fields before tring to make the value concrete, because this will
require to revisited some fields to generate the actual values.
Problematic structure
```
{
"path": {
"home": "/var",
"logs" "${path.home}"
}
"output" : {
"file": "${path.logs}"
}
}
```
We could also improve the caching mechanism to solve that issues, but
this seems to be the simplest fix to do.
Fixes: elastic/beats#6214
> Fix an issue when a cyclic reference was incorrectly detected when multiple reference was used.

- CHANGELOG.md
- reify.go
- unpack.go
Unpacking into a ucfg.Config (or convertible structure) has priority
over custom Unpack methods. Both, ucfg.Config and Unpacker interface
have an `Unpack` method with signature `Unpack(interface{}) error`. The
difference between these too is, `(*ucfg.Config).Unpack` gets the target
structure as parameter, while the `Unpacker` interface gets the config
as parameter and the target is the method receiver.
=> When testing for the Unpacker interface, we must first make sure the
method receiver is not of type `ucfg.Config`.
> Correct order when unpacking into ucfg.Config

- CHANGELOG.md
- merge.go
- merge_test.go
- opts.go
- reify.go
- reify_test.go
- ucfg.go
- util.go
Improve array merging by configuring the 'merge' strategy either globally or via struct tags. Overwriting the merge option in a struct-tags will apply the merge rule for all sub-structures.
Merge rules:
- *merge (default)*: Merge values and values in arrays. Struct tag option: `merge`, global: none (default behavior)).
- *replace*: Replace *Config objects containing dicionaries or arrays. Struct tag option: `replace`, global: `ReplaceValues`.
- *append*: Merge dictionaries, but append arrays to existing arrays. Struct tag option: `append`, global: `AppendValues`.
- *prepend*: Merge dictionaries, but prepend arrays to existing arrays. Struct tag option: `prepend`, global: `PrependValues`.
> Array merging

- CHANGELOG.md
- merge.go
- merge_test.go
When escaping `$`, the escape symbol should be removed when unpacking the configuration.
> Fix escape character not removed from escaped string

- CHANGELOG.md
- opts.go
- ucfg_test.go
This resolver will return the key wrapped in the field reference syntax.
This allow you to hide sensitive information present in the environment
or by other resolvers.
> Adding a ResolverNOOP

- CHANGELOG.md
- path.go
- ucfg.go
- ucfg_test.go
Add Has method to the Config object. Has can walk a given path and reports true if there is a setting or namespace for the given path. Has returns an error if the namespace can not be walked in completion due to an intermediare not being an object/array.
> Add (*Config).Has

- CHANGELOG.md
- error.go
- error_test.go
- opts.go
- path.go
- testdata/error/message/no_parse.golden
- testdata/error/message/no_parse_nested.golden
- testdata/error/message/no_parse_nested_w_meta.golden
- testdata/error/message/no_parse_w_meta.golden
- types.go
- ucfg.go
- ucfg_test.go
Add method to config object to remove settings by fully qualified name. This can remove single settings, but complete namespaces as well.
> Add (*Config).Remove method

- README.md
Readme example wasn't compiling.
> Make README.md example compile

- CHANGELOG.md
- reify.go
- validator_test.go
This adds more validation tests to cover all types and structs that where not originally covered. With the added test `Validate` on `map[string]X` was not being called when defined, that is fixed in this PR.
Fixes elastic/go-ucfg#136
> Add more validation tests, fixing issue where Validate was not being called on maps.

- CHANGELOG.md
- flag/value.go
- internal/parse/parse.go
- internal/parse/parse_test.go
- opts.go
- parse/parse.go
- parse/parse_test.go
- reify_test.go
- structs_test.go
- types.go
- ucfg_test.go
- variables.go
Currently `internal/parse` handles the values from the environment variable just like values from the configuration file. This PR changes the parser to limit environment variable parsing to not parse object notation.
This is a **breaking** change because if any environment relies on this behavior it would break them. I question if this is correct way to solve the bug.
Really the bug could be solved by ensuring that the environment variable is single quoted:
```
export ENV_VAR="'{user}'"
```
I would be okay with closing this PR and closing the bug with this comment.
> Fix parsing of environment variables to prevent object parsing. #132

- CHANGELOG.md
- initializer.go
- initializer_test.go
- reify.go
- types.go
- ucfg.go
- ucfg_test.go
- unpack.go
- unpack_test.go
Call the `InitDefaults` during `Unpack` when a structure implements the `Initializer` interface. This allows a structure to define its default values without having to push the defaults into the loaded configuration.
Closes #104
> Add call to InitDefaults when structs implement Initializer interface during Unpack.

- CHANGELOG.md
- reify.go
- reify_test.go
- util.go
- validator.go
- validator_test.go
When unpacking into an object that already has values present but the configuration doesn't contains values for those objects still apply validation to the objects existing values. This is to ensure that even defaults that might already be set in the object that is passed to Unpack adheres to the same validation rules that the configuration must adhere to.
This also contains a fix on how validateRequired would return an ErrEmpty error instead of an ErrRequired. When using the `validate:"required"` tag the error message should match the tag applied.
Closes #42
> Apply validation to default values even when values do not come from the configuration

- CHANGELOG.md
- validator.go
- validator_test.go
Prevents Validate from being called when value is a pointer or interface and is nil.
Closes #144
> Prevent Validate from being called when value is a pointer or interface and is nil.

- CHANGELOG.md
- error.go
- reify.go
- validator.go
- validator_test.go
Fixes issue where the `nonzero` validator would fail when the array or slice was `nil` value.
This also includes fixes for map types where nonzero or required would not validate them correctly.
Closes elastic/go-ucfg#147
> Fix nonzero validator to not validate nil array or slices.

- CHANGELOG.md
- merge.go
- merge_test.go
- opts.go
Adds the ability to adjust merging behavior of configs per fields defined in configurations.
Below is the user experience that this change provides:
```
cfg.Merge(
other,
ucfg.FieldReplaceValues("paths"),
ucfg.FieldAppendValues("processors"),
)
```
This would allow a `paths` field to be replaced with any values from `other` and the `processors` field to be appended with values from `other`. Indexes into arrays can also be used to adjust the merging behavior at that index in the array (eg. `FieldAppendValues("processors.2.add_tags.tags"`). 
In the case that the depths of the fields are unknown but that behavior should always occur when fields of that name are reached in the merging process then the `**.{name}` selector can be used.
`ucfg.FieldReplaceValues("**.paths")` will ensure that …
> Add ability to adjust merging behavior of configs per fields defined in configurations

- ucfg_test.go
This fixes a dropped error in `TestCyclicReferenceShouldFallbackToOtherResolvers()`.
> Fix Dropped Test Error

- validator_test.go
Hi, @urso.
I've dipped my toe in the water of removing `assert`, as mentioned in https://github.com/elastic/go-ucfg/issues/156.
This removes `testify/assert` from only one test file in the `ucfg` package, and it brings in `go-spew` to improve the readability of test failures.
If this approach looks good to you, I'm happy to keep going, preferably one entire package per PR.
> Remove testify/assert from Validator Tests

- CHANGELOG.md
- cfgtest/unpack.go
- error_test.go
- reify.go
- testdata/error/message/invalid_duration_w_meta.golden
- testdata/error/message/invalid_duration_wo_meta.golden
- testdata/error/message/invalid_regexp_w_meta.golden
- testdata/error/message/invalid_regexp_wo_meta.golden
- validator_test.go
- yaml/yaml_test.go
This PR fixes the issue reported in https://github.com/elastic/go-ucfg/issues/159 .
Check if the target is valid, before setting the value. The target field will stay `nil`.
/cc @ruflin
> Fix: check if target is valid

- initializer_test.go
Only an additional test for #141, I was wondering if this works too with structs in arrays, and it seems to :slightly_smiling_face:
> Add test for struct with array defaults initializer

- validator.go
It seems the error messages for min/max validators are backwards. Say I have a field with `validate:"min=1, max=5"`.
Supplying a value of 0, I get the error message:
```
Error processing configuration: requires value < 1 accessing 'field.name'
```
I would expect that to say `...value >= 1...`
Supplying a value of 6, I get the error message:
```
Error processing configuration: requires value > 5 accessing 'field.name'
```
I would expect that to say `...value <= 5...`
> Fix min/max validator error messages

- hjson/hjson_test.go
Explicit error check can be easily replaced with `require.NoError` which exactly does the same thing, i.e. the package `require` implements the same assertions as the `assert` package but stops test execution when a test fails:- When constructing a new configuration object from the HJSON bytes that is passed in as input, it makes more sense to check the error by using `require.NoError`; we can stops test execution right way when the assertion fails. This is applicable while performing an unpack. Aside from that, it is always safer to check the length of options unpacked into the slice right before accessing the elements based on index to avoid panic.
> Use require.NoError to stop test execution when a test fails

- json/json_test.go
Explicit error check can be easily replaced with `require.NoError` which does exactly the same thing, i.e. the package require implements the same assertions as the assert package but stops test execution when a test fails:- When constructing a new configuration object from the JSON bytes that is passed in as input, it makes more sense to check the error by using `require.NoError`; we can stop test execution right way when the assertion fails. This is applicable while performing an unpack. Aside from that, it is always safer to check the length of options unpacked into the slice right before accessing the elements based on index to avoid panic. Also replaced empty slice declaration via literal from TestArray with nil slice.
> Refactor tests in json package to make use of require.NoError to stop test execution when a test fails

- flag/file_test.go
- flag/value_test.go
Use of assert.True is preferable over assert.Equal in places where a specified value needs to be asserted against true or false. Field validations encapsulated inside the checkFields have been refactored to adhere to this standard.
When the flag parsing ends up with an error or if there is any failure in getting the child configuration, we don’t need to fall through subsequent field validation and need to fail the test immediately to get rid of potential panic instead. This change has been incorporated into the following tests:
- TestFlagFileParsePrimitives
- TestFlagFileParseOverwrites
- TestFlagValuePrimitives
- TestFlagValueLast
- TestFlagValueMissing
- TestFlagValueNested
- TestFlagValueList
- TestMergeFlagValueNewList
> Refactor flag related tests and include conditional assertions in required places

- diff/keys_test.go
The assert.NoError has been replaced with require.NoError in the following tests to avoid potential panic and to stop the test execution right away whilst unpack fails:
- TestDiff
- TestConfigurationWithAddedCompareConfigs
- TestConfigurationWithRemovedKey
- TestConfigurationWithAddedAndRemovedKey
- TestConfigurationHasNotChanged
> Avoid potential panic in keys test and stop the test by using assert.NoError

- initializer_test.go
There was a typo in the structNoInitializer struct definition which is corrected in this PR. Aside from that, assert.NoError has been replaced with require.NoError to avoid potential panic and to stop the test execution right away whilst unpack fails. Following tests were affected:
- TestInitDefaultsPrimitive
- TestInitDefaultsPrimitiveSet
- TestInitDefaultsMap
- TestInitDefaultsMapUpdate
- TestInitDefaultsMapReplace
- TestInitDefaultsSingle
- TestInitDefaultsNested
- TestInitDefaultsNestedEmpty
- TestInitDefaultsPtrNestedEmpty
- TestInitDefaultsStructWithArray
> Avoid potential panic and to stop the test execution right away whilst unpack fails

- yaml/yaml_test.go
It is reasonable to refactor the mustNewConfig function by changing its signature to accept config options and make it reusable across other tests inside the yaml package; It was only used inside the empty collections tests.
> Refactor mustNewConfig to make it reusable across other tests inside yaml package

- error.go
Fixed typo in ErrArraySizeMismatch defined in error.go
> Fix typo in ErrArraySizeMismatch defined in error.go

- ucfg.go
Fixed a typo in code comments against Config struct inside ucfg.go
> Fix typo in code comments against Config struct inside ucfg.go

- hjson/hjson_test.go
Provided mustNewConfig and mustUnpack for Hjson config tests to promote reusability
> Provide mustNewConfig and mustUnpack for Hjson config tests to promote reusability

- .ci/Jenkinsfile
- CHANGELOG.md
- NOTICE.txt
- types.go
- yaml/yaml_test.go
Fixes #188 
This adds a special case for empty arrays when reifying configuration objects during Unpack. This is a breaking change compared to existing behaviour as visible in the test cases I adjusted. The original issue #160 that introduced said tests is however still addressed.
> Preserve empty untyped arrays when reifying

- CHANGELOG.md
- NOTICE.txt
- parse/parse.go
- parse/parse_test.go
The new flag stops the parser from building arrays automatically when
top level elements are separated with commas. This flag converts parsing
into an actual no-op, passing through the input unmodified. This mode is
necessary when parsing values that may legitimately contain special
characters, like secrets.
This is the first step in fixing https://github.com/elastic/beats/issues/29789. A follow up change in beats will follow to start ignoring commas when loading from the keystore.
Draft beats PR with a failing test that will pass with these changes: https://github.com/elastic/beats/pull/31487
> Add flag to ignore commas when parsing.

- NOTICE.txt
- getset.go
- merge.go
- opts.go
- path.go
- reify.go
- ucfg.go
- ucfg_test.go
- variables.go
- variables_test.go
This is one of the ways to fix the issue with configuration parsing where the keys are numeric strings.
Couple of example of problem when creating configuration with NewFrom API call:
INPUT:
```
{"a":{"9223372036854775807":{}}}
```
RESULT:
```
panic: runtime error: makeslice: len out of range [recovered]
panic: runtime error: makeslice: len out of range
```
INPUT:
```
{"a":{"9223372036854":{}}}
```
RESULT:
```
runtime: out of memory: cannot allocate 147573956411392-byte block (3833856 in use)
fatal error: out of memory
```
**Solution**
The library is quite old, so being overly cautious here in order to avoid breaking the original behavior. One of the possible approaches here is to preserve the same behavior as before, put some protection from large allocations and OOM, allow the user to …
> Fix numeric configuration keys handling

- NOTICE.txt
- opts.go
- reify_test.go
- types.go
Fixes https://github.com/elastic/go-ucfg/issues/196
This is a rather cautious fix for the above issue, as the issue itself (Parsing a config with `VarExp` causes us to also treat any string with a `,` as an array) is so odd that I'm not sure if there are any secret, undocumented use cases that I might break. Therefore this is an opt-in fix, requiring code to send the `IgnoreCommas` option to `Unpack` in order for us to not trigger this bug.
This also includes a number of tests that demonstrate the issue.
> Add exported IgnoreCommas option to fix parser issues

- opts.go
Followup to #192, `elastic-agent` has a `getOptions()` method that checks any options passed to the underlying ucfg calls. It expects the options to be of type `Option`. Alas, without explicitly setting the type in the declaration, go will read the type as `func(*option)` instead of the `Option` type alas.
> set IgnoreCommas to Option type

- .github/workflows/ci.yml
- NOTICE.txt
See https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/#artifact-actions-v3-brownouts
> github-actions: actions/upload-artifact@v3 will be retired by January 30th, 2025

- merge.go
- opts.go
- path.go
- path_test.go
- variables.go
- variables_test.go
👋 team,
A user reported an issue in https://github.com/elastic/cloud-on-k8s/issues/8499 because it is not possible to escape dots in keys.
This small PR is an attempt to implement an escape mechanism similar to what is supported by Kibana: https://github.com/elastic/kibana/pull/178841
In order to preserve the existing behaviour the escape mechanism is enabled only if a related option is explicitly set to `true`. 
If possible we would like to get it in the next ECK release, which should happen in a few days. Please let me know if you have any feedback, opinion or thoughts about adding this feature or any workarounds I might have missed.
Thanks! 🙇 
CC @elastic/serverless-applications
> Add an option to escape paths
